<?php
    $userGuide = Mage::helper('storepickup')->__('
	Store Pickup extension is used as a Magento shipping method. Follow these steps to configure the module:<br />
        1. To add/ import stores with location, time schedule and other information, go to <strong>Store Pickup</strong> -> <strong>Manage Stores</strong><br />
        2. To set days off for store(s), go to <strong>Store Pickup</strong> -> <strong>Manage Holidays</strong><br />
        3. To set days with special working time for store(s), go to <strong>Store Pickup</strong> -> <strong>Manage Special Days</strong><br />
        4. To configure Store Pickup extension, go to <strong>Systems</strong> -> <strong>Configuration</strong> -> <strong>Shipping Methods</strong> -> <strong>Store Pickup</strong><br />
    ');
?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('storepickup')->__('General Instructions') ?></h4>        
    </div>
    <div class="fieldset ">
        <div class="hor-scroll">
            <?php echo $userGuide ?>
        </div>
    </div>
    
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('storepickup')->__('Instructions to create Google Map API Key') ?></h4>        
    </div>
    <div class="fieldset ">
        <div class="hor-scroll">
            <?php echo '1. Visit the APIs Console at'?> <a href="https://code.google.com/apis/console" target="_blank"><?php echo 'https://code.google.com/apis/console' ?></a><?php echo ' and log in with your Google Account.' ?>
            <br />
            <?php echo '2. Click on the <strong>APIs</strong> link in the left menu.' ?>
            <br />
            <?php echo '3. Activate the <strong>Google Maps JavaScript API v3</strong>, <strong>Distance Matrix API</strong>, <strong>Geocoding API</strong> services.' ?>
            <br />
            <br />
            <img width="80%" src="<?php echo Mage::getBaseUrl('media').'storepickup/guide/google-api-active.png' ?>" title="<?php echo $this->__('Google API Active') ?>" />
            <br />
            <br />
            <?php echo '4. Click on the <strong>Credentials</strong> link in the left menu,  the "CREATE NEW KEY" in the "Public API access" section to create Google Map API Key for browser apps.' ?>
            <br />
            <br />
            <img width="80%" src="<?php echo Mage::getBaseUrl('media').'storepickup/guide/create-key.png' ?>" title="<?php echo $this->__('Google API Active') ?>" />
        </div>
    </div>
</div>